# Generated by Django 5.2.15 on 2026-06-24 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_datasource_feed_url_datasource_ingestion_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(choices=[('regulatory', 'Regulatory'), ('economic', 'Economic'), ('full', 'Full')], max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('items_fetched', models.PositiveIntegerField(default=0)),
                ('items_new', models.PositiveIntegerField(default=0)),
                ('items_failed', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='IngestedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=512)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=2048)),
                ('raw_content', models.TextField(blank=True)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('indexed', 'Indexed'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='new', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('evidence_id', models.PositiveIntegerField(blank=True, null=True)),
                ('regulatory_change_id', models.PositiveIntegerField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingested_items', to='core.datasource')),
            ],
            options={
                'ordering': ['-fetched_at'],
                'constraints': [models.UniqueConstraint(fields=('data_source', 'external_id'), name='unique_source_external_id')],
            },
        ),
    ]
