# Generated by Django 5.2.15 on 2026-06-24 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryRiskSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('political_risk', models.DecimalField(decimal_places=2, max_digits=5)),
                ('regulatory_risk', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trade_risk', models.DecimalField(decimal_places=2, max_digits=5)),
                ('summary', models.TextField(blank=True)),
                ('as_of', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_snapshots', to='core.country')),
            ],
            options={
                'ordering': ['-as_of'],
                'get_latest_by': 'as_of',
            },
        ),
        migrations.CreateModel(
            name='EconomicIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_type', models.CharField(choices=[('gdp_growth', 'GDP Growth'), ('inflation', 'Inflation'), ('fx_rate', 'FX Rate'), ('trade_balance', 'Trade Balance'), ('corruption_index', 'Corruption Perception'), ('electricity_access', 'Electricity Access'), ('custom', 'Custom')], max_length=32)),
                ('label', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('period', models.DateField(help_text='Observation date or period end')),
                ('source_url', models.URLField(blank=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='core.country')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicators', to='core.datasource')),
            ],
            options={
                'ordering': ['-period'],
                'indexes': [models.Index(fields=['country', 'indicator_type', '-period'], name='intelligenc_country_031aa6_idx')],
            },
        ),
    ]
