# Generated by Django 5.2.15 on 2026-06-24 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'industries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MarketEntryPlaybook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_country', models.CharField(help_text='ISO country code, e.g. DE', max_length=2)),
                ('company_description', models.TextField(blank=True)),
                ('estimated_timeline_weeks', models.PositiveIntegerField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='playbooks', to='playbooks.industry')),
                ('target_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbooks', to='core.country')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaybookStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('registration', 'Registration'), ('tax', 'Tax Obligations'), ('import', 'Import Rules'), ('permit', 'Permits & Licenses'), ('payment', 'Payment Options'), ('partner_risk', 'Local Partner Risks'), ('document', 'Required Documents'), ('compliance', 'Compliance Checklist'), ('logistics', 'Logistics / Customs')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('source_url', models.URLField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='playbooks.marketentryplaybook')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
