# Generated by Django 5.2.15 on 2026-06-24 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_datasource_feed_url_datasource_ingestion_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=255)),
                ('activity_type', models.CharField(choices=[('import', 'Import'), ('export', 'Export'), ('transit', 'Transit'), ('registration', 'Business Registration'), ('licensing', 'Licensing'), ('customs', 'Customs Clearance'), ('other', 'Other')], default='other', max_length=32)),
                ('summary', models.TextField(blank=True)),
                ('source_url', models.URLField()),
                ('source_portal', models.CharField(default='EAC TIP', max_length=100)),
                ('estimated_days', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_cost', models.CharField(blank=True, max_length=255)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_procedures', to='core.country')),
            ],
            options={
                'ordering': ['country__code', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TradeProcedureStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('responsible_agency', models.CharField(blank=True, max_length=255)),
                ('documents_required', models.JSONField(blank=True, default=list)),
                ('estimated_days', models.PositiveIntegerField(blank=True, null=True)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='trade.tradeprocedure')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='tradeprocedure',
            index=models.Index(fields=['country', 'activity_type'], name='trade_trade_country_ce2d4e_idx'),
        ),
    ]
