# Generated by Django 5.2.15 on 2026-06-24 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('has_sufficient_evidence', models.BooleanField(default=False)),
                ('refusal_reason', models.TextField(blank=True, help_text='Set when the assistant cannot answer without evidence.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'assistant queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('source_url', models.URLField()),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('content', models.TextField()),
                ('published_at', models.DateField(blank=True, null=True)),
                ('indexed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-indexed_at'],
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excerpt', models.TextField()),
                ('relevance_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='assistant.assistantquery')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='assistant.evidencedocument')),
            ],
            options={
                'ordering': ['-relevance_score'],
            },
        ),
    ]
