# Generated by Django 5.2.15 on 2026-06-24 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantquery',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_queries', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='assistantquery',
            name='retrieval_method',
            field=models.CharField(default='hybrid', max_length=32),
        ),
        migrations.AddField(
            model_name='evidencedocument',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidencedocument',
            name='embedding_dims',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
