# Generated by Django 5.2.15 on 2026-06-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_evidencedocument_embedding_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='relevance_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
