# Generated by Django 5.2.15 on 2026-06-24 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeAlertSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(blank=True, choices=[('tax', 'Tax'), ('investment', 'Investment'), ('customs', 'Customs / Import-Export'), ('eac_trade', 'EAC Trade'), ('data_protection', 'Data Protection'), ('labor', 'Labor / Contractor'), ('other', 'Other')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_subscriptions', to='core.country')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('business_impact', models.TextField()),
                ('required_action', models.TextField()),
                ('category', models.CharField(choices=[('tax', 'Tax'), ('investment', 'Investment'), ('customs', 'Customs / Import-Export'), ('eac_trade', 'EAC Trade'), ('data_protection', 'Data Protection'), ('labor', 'Labor / Contractor'), ('other', 'Other')], max_length=32)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('source_url', models.URLField()),
                ('published_at', models.DateField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_changes', to='core.country')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='core.datasource')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['country', 'category', '-detected_at'], name='regulatory__country_60bf50_idx')],
            },
        ),
    ]
