# Generated by Django 5.2.15 on 2026-06-24 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_eac_member', models.BooleanField(default=False)),
                ('currency_code', models.CharField(blank=True, max_length=3)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('tax_authority', 'Tax Authority'), ('investment_authority', 'Investment Authority'), ('customs', 'Customs'), ('eac_trade', 'EAC Trade Portal'), ('data_protection', 'Data Protection'), ('labor', 'Labor / Employment'), ('central_bank', 'Central Bank'), ('trade_portal', 'Trade Information Portal'), ('world_bank', 'World Bank'), ('imf', 'IMF'), ('rss', 'RSS Feed'), ('other', 'Other')], max_length=32)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='core.country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
