# Generated by Django 5.2.15 on 2026-06-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='feed_url',
            field=models.URLField(blank=True, help_text='RSS/Atom feed URL when different from the portal URL.'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='ingestion_config',
            field=models.JSONField(blank=True, default=dict, help_text='Fetcher config, e.g. {"type": "rss"} or {"type": "html_list", "list_url": "..."}'),
        ),
    ]
